# 1.1. 파이썬 모듈

In [8]:
# system module
import sys
sys.version_info

sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

In [9]:
# numpy & pandas module
import pandas as pd
import numpy as np


In [10]:
# visualization module
import matplotlib as mpl
import seaborn as sns
import pyecharts as pyc

In [11]:
# 머신 러닝
import sklearn as sk

# 1.2. 파이썬 변수와 기본 문장

In [27]:
'''파이썬 변수'''
# 전역 변수
x=10
s='happy'
print(globals()['x'])
print(globals()['s'])

10
happy


In [31]:
'''제어문'''
# 제어문 1
if 10>5:
    print('참 입니다')
else:
    print('거짓 입니다.')
    
# 제어문 2
print('참 입니다.') if True else print("거짓 입니다.")

참 입니다
참 입니다.


In [36]:
'''순환문'''
# for 순환문
result=0
for i in range(1, 5):
    result+=i
print("for 순환문 결과:" + str(result))

# while 순환문
result, i=0, 1
while i < 5:
    result += i
    i += 1
print("while 순환문 결과: " + str(result))

for 순환문 결과:10
while 순환문 결과: 10


# 1.3. 파이썬 함수

In [45]:
'''함수 정의'''
# 구조
# 함수를 정의하면 [지역이름공간]과 [초기값 관리공간]으로 나뉘어 저장되는데, 초기 값인 x=10, y=30은 [초기값 관리공간]에 저장되고, func(20, y=80)을 쓸 때 20과 80은 [지역이름공간]에 저장된다. 
def func(x=10, y=30):
    return x+y
print(func())
print(func(20, y=80))    

40
100


In [81]:
'''가변 인자'''
def var_args(*args):
    print(args)
    return sum(args)

var_args(1, 2, 3, 4, 5)

# 선언할 때: *args
# 사용할 때: args => 튜플 형태
# sum()의 매개변수로, list와 tuple이 들어갈 수 있는데 tuple이 들어갔으므로 계산이 되는 상태

(1, 2, 3, 4, 5)


15

In [83]:
'''가변 키워드 인자'''
def var_kwargs(**kwargs):
    print(*kwargs) # key 값 출력
    print(kwargs) # key:value 맵핑 값 출력
    return sum([*kwargs.values()])

var_kwargs(a=1, b=2, c=3, d=4, e=5)
# sum()의 매개변수로, list와 tuple이 들어갈 수 있는데 dictionary 형태로 값이 들어가 있으니[_dict_]로 변환해서 sum하기

a b c d e
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


15

# 1.4. 파이썬 클래스와 객체

In [99]:
'''클래스 사용법'''
# object class를 상속받은 Klass에서는 age, name을 입력받고, getName()과 getAge()메서드를 가지고 있음.
class Klass(object):
    
    # init은 객체의 속성을 초기화 하는 역할임.
    def __init__(self,age, name): # 메서드 정의(self 매개변수 사용)
        self.name=name
        self.age=age
        
    def getName(self): # 메서드 정의(self 매개변수 사용)
        return self.name
    
    def getAge(self): # 메서드 정의(self 매개변수 사용)
        return self.age

# k 객체 생성   
k=Klass(23, "김가영")
print(k.name)
print(k.getName())
print(k.getAge())

# n 객체 생성
n=Klass(20, "최웅")
print(n.name)
print(n.getName())
print(n.getAge())

# 메서드 확인
print(Klass.__init__)
print(Klass.__init__(k, 18, '김윤영'))
print(k.getName(), k.getAge())

김가영
김가영
23
최웅
최웅
20
<function Klass.__init__ at 0x000001FBA2F26280>
None
김윤영 18


# 1.5. 파이썬 내장 숫자클래스

In [101]:
x=1
print(isinstance(x, int))
y=1.1
print(isinstance(y, float))

True
True


In [102]:
a=float(1)
print(a)

1.0


In [103]:
b=int(a)
print(b)

1


In [104]:
float('1.1'), int('1')

(1.1, 1)

In [108]:
# 문자열 내에 숫자만 존재하는지 확인
'1.1'.isdigit()

False

In [110]:
try:
    int('11')
except Exception as e:
    print(e)

# 1.6. 문자열

In [124]:
s='happy' #유니코드 문자열
b=b"happy" # 바이트 문자열은 영어와 숫자로만 구성, 쌍따옴표 앞에 b를 붙인다.

In [125]:
isinstance(s, str), isinstance(s, bytes) #유니코드 문자열 O, 바이트 문자열 X

(True, False)

In [126]:
isinstance(b, bytes), isinstance(b, str) #유니코드 문자열 X, 바이트 문자열 O #유니코드 문자열을 암호화하면 바이트 문자열이 만들어짐


(True, False)

In [130]:
s[0], b[0] # 바이트 문자열은 결과를 숫자로 반환

('h', 104)

In [131]:
chr(b[0])

'h'

In [132]:
s[-1], chr(b[-1])

('y', 'y')

In [133]:
try:
    s[0]=100
except Exception as e:
    print(e)

'str' object does not support item assignment


In [134]:
try:
    b[0] = 100
except Exception as e:
    print(e)

'bytes' object does not support item assignment


In [135]:
bs = s.encode()
isinstance(bs, bytes)

True

In [136]:
len(bs)

5

In [141]:
bs=bs.decode()

In [142]:
isinstance(bs, str)

True

# 1.7. 파이썬 리스트 클래스

In [163]:
from abc import *

# 추상 클래스는 파생 클래스가 반드시 구현해야하는 method를 @abstracmethod로 정의해줄 수 있음.
# 추상클래스의 추상 메서드를 빈 메서드로 만드는 이유: 추상클래스는 인스턴스(객체, James)를 만들 수 없기 때문에!
class StudentBase(metaclass=ABCMeta):
    
    @abstractmethod
    def study(self):
        pass
    
    @abstractmethod
    def go_to_school(self):
        pass
    
class Student(StudentBase):
    
    def study(self):
        print('공부 하기')
        
    def go_to_school(self):
        print('학교 가기')
        
james = Student()
james.study()
james.go_to_school()

공부 하기
학교 가기


In [169]:
import collections.abc as abc #자료구조에 대한 추상클래스 모듈 사용

print(abc.Sequence.__abstractmethods__) #Sequence클래스에 대한 추상 메서드 확인
print(abc.MutableSequence.__abstractmethods__) #mutableSequence클래스에 대한 추상 메서드 확인
print(issubclass(list, abc.Sequence)) # list가 abc.Sequence의 하위클래스임
print(issubclass(abc.Sequence, list)) # abc.Sequence가 list의 하위클래스가 아님

frozenset({'__getitem__', '__len__'})
frozenset({'__setitem__', '__getitem__', 'insert', '__len__', '__delitem__'})
True
False


In [171]:
x=list((1, 2, 3, 'a'))
print(x)
isinstance(x, list)


[1, 2, 3, 'a']


True

In [172]:
print(x[0])
print(x[1])
print(x[2])
print(x[3])

1
2
3
a


In [173]:
try:
    x[10]
except Exception as e:
    print(e)

list index out of range


In [178]:
print(len(x))
print(x[len(x)-1])

4
a


In [185]:
x=[1, 2, 3, 4]
x.append(10)
print(x)
x.append( 2)
print(x)

[1, 2, 3, 4, 10]
[1, 2, 3, 4, 10, 2]


In [186]:
x=[1, 2, 3, 4]
x.extend([5, 6, 7, 8])
print(x)

[1, 2, 3, 4, 5, 6, 7, 8]


In [189]:
x.remove(5)
print(x)

[1, 2, 3, 4, 6, 7, 8]


In [190]:
x.pop()
print(x)

[1, 2, 3, 4, 6, 7]


In [191]:
x.insert(0, 100) # 0번째 index에 100을 insert하기
print(x)

[100, 1, 2, 3, 4, 6, 7]


In [195]:
x.pop(0)
print(x)

[3, 4, 6, 7]


In [196]:
x[0]=2948

In [198]:
print(x)
del x[0]
print(x)

[2948, 4, 6, 7]
[4, 6, 7]


In [200]:
x = [1, 2, 3, 4, 5, 6]
y = x[3:6] # x[3], x[4], x[5] 로 값을 초기화
print(y)

[4, 5, 6]


# 1.8. 배열(array)모듈의 배열

In [207]:
# 배열을 만들려면 array 모듈을 import해야함
import array

In [209]:
a=array.array('i',[1, 2, 3, 4, 5])
print(a)
print(type(a))


array('i', [1, 2, 3, 4, 5])
<class 'array.array'>


In [210]:
import collections.abc as abc

issubclass(type(a), abc.MutableSequence) # Sequence특징을 가졌지만 실제 구현은 추상 클래스의 모든 기능을 전부 구현하지는 않았음을 알 수 있음.

False

In [213]:
a.typecode, a.itemsize # 배ㅕㅇㄹ의 타입코드와 원소의 바이트 크기 확인 => array모듈에서만 사용할 수 있음.

('i', 4)

In [216]:
a.buffer_info() # 배열의 레퍼런스 원소의 개수 확인

(2180283966224, 5)

In [218]:
# 배열의 원소 검색 -> list와 동일
a[0]
a[-1]
len(a)

5

In [220]:
try:
    a[5] = 100
except Exception as e:
    print(e)

array assignment index out of range


In [221]:
a.append(100)
print(a)

array('i', [1, 2, 3, 4, 5, 100])


In [225]:
a.extend([6, 7, 8])
b=a.tolist() #a 를 리스트로 변환

In [226]:
type(a), type(b)

(array.array, list)

In [228]:
ab=a.tobytes() #배열을 바이트로 변환!
print(ab)
print(len(ab)/len(a)) # 배열보다 4배의 길이임.

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00d\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00'
4.0


In [230]:
print(a)
a.insert(0, 999)
print(a)

array('i', [999, 1, 2, 3, 4, 5, 100, 6, 7, 8, 6, 7, 8, 6, 7, 8])
array('i', [999, 999, 1, 2, 3, 4, 5, 100, 6, 7, 8, 6, 7, 8, 6, 7, 8])


In [231]:
print(a[-1])
print(a.pop())

8
8


In [232]:
print(a)
a.remove(2)
print(a)

array('i', [999, 999, 1, 2, 3, 4, 5, 100, 6, 7, 8, 6, 7, 8, 6, 7])
array('i', [999, 999, 1, 3, 4, 5, 100, 6, 7, 8, 6, 7, 8, 6, 7])


In [234]:
print(a.index(100)) #100의 index가 무엇인지 확인하는 메서드
print(a.index(999), a.count(999)) # 999의 index가 무엇인지, 999는 몇 개가 있는지 확인하는 메서드

6
0 2


In [235]:
a.reverse() #원소를 반대로 배열
print(a)

array('i', [7, 6, 8, 7, 6, 8, 7, 6, 100, 5, 4, 3, 1, 999, 999])


In [236]:
a+a

array('i', [7, 6, 8, 7, 6, 8, 7, 6, 100, 5, 4, 3, 1, 999, 999, 7, 6, 8, 7, 6, 8, 7, 6, 100, 5, 4, 3, 1, 999, 999])

In [237]:
a*2

array('i', [7, 6, 8, 7, 6, 8, 7, 6, 100, 5, 4, 3, 1, 999, 999, 7, 6, 8, 7, 6, 8, 7, 6, 100, 5, 4, 3, 1, 999, 999])

In [238]:
b=[1, 2, 3] # 리스트도 가능
b+b

[1, 2, 3, 1, 2, 3]

# 1.9. 넘파이 모듈의 다차원 배열

In [239]:
import numpy as np
np.__version__

'1.20.3'

In [240]:
a=np.array([1, 2, 3, 4])

In [241]:
a

array([1, 2, 3, 4])

In [242]:
print(a) # 리스트와 달리 쉼표가 없이 출력됨.

[1 2 3 4]


In [244]:
import collections.abc as abc
issubclass(type(a), abc.MutableSequence)

False

In [245]:
abc.MutableSequence.__abstractmethods__
dir(np.ndarray).count('insert')

0

In [250]:
# ndarray 클래스는 데이터와 메타정보를 분리해서 관리함
# 메타벙보: dtype, ndim, shape, stides, data
a=np.array([[1, 2, 3],[8, 9, 0]])
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.itemsize) # 원소 하나의 바이트 크기
print(a.data) # 다차원 배열을 만들면 데이터는 메모리에 로딩되는데, 이 메모리를 관리하는 속성이 a.data이다.
print(a.strides) # 확장 가능한 정도

int32
2
(2, 3)
4
(12, 4)


In [251]:
# 동일한 명령어
print(a)
print(a.data.obj)

[[1 2 3]
 [8 9 0]]
[[1 2 3]
 [8 9 0]]


In [252]:
a.data.obj

array([[1, 2, 3],
       [8, 9, 0]])

#### 다차원 배열의 자료형 처리

In [255]:
happy = np.dtype(np.int32)
print(type(happy))
happy.char, happy.kind, happy.itemsize # happy에 들어가는 자료형 을 I와i로 저장하고 바이트 크기인 itemsize를 4를 저장한다.

<class 'numpy.dtype[int32]'>


('l', 'i', 4)